apiVersion: apps/v1
kind: Deployment
metadata:
  name: saltdash
  labels: 
    app: saltdash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saltdash
  template:
    metadata:
      labels:
        app: saltdash
    spec:
      containers:
      - image: batgranny/saltdash
        name: saltdash
        ports:
        - containerPort: 80
        - containerPort: 3306
        
---

apiVersion: v1
kind: Service
metadata:
  name: saltdashsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
      app: saltdash

